[package]
name = "seigi"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Fundamental web UI components written in Rust"
homepage = "https://github.com/kappa8719/seigi"
repository = "https://github.com/kappa8719/seigi"


[workspace]
members = ["seigi_toast"]
