[package]
name = "seigi"
version = "0.2.0"
edition = "2024"
license = "MIT"
description = "Fundamental web UI components written in Rust"
homepage = "https://github.com/kappa8719/seigi"
repository = "https://github.com/kappa8719/seigi"


[workspace]
members = ["seigi_*"]

[workspace.dependencies]
seigi_toast = { path = "seigi_toast", version = "0.2.0" }
web-sys = { version = "0.3", features = ["Document", "Window", "PopStateEvent", "HtmlAnchorElement", "NodeList", "CssStyleDeclaration", "ViewTransition", "HtmlStyleElement", "Text", "ResizeObserver"] }
js-sys = "0.3"
wasm-bindgen = "0.2"
gloo = "0.11.0"

[dependencies]
seigi_toast.workspace = true
