[package]
name = "seigi_focus"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Low overhead focus management"
homepage = "https://github.com/kappa8719/seigi/seigi_focus"
repository = "httsps://github.com/kappa8719/seigi"

[dependencies]

